-- Aurora Homepage V3.5：评论设备类型、公开图片与站主回复
-- 在 Supabase Dashboard > SQL Editor 中完整执行一次。
-- 本迁移新建 V2 评论表，不修改旧 public_comments / submit_feedback，历史评论可继续读取。

begin;

create extension if not exists pgcrypto;

create table if not exists public.feedback_messages_v2 (
  id bigint generated by default as identity primary key,
  display_name text,
  category text not null,
  device_type text not null,
  content text not null,
  contact text,
  wants_public boolean not null default false,
  image_path text,
  upload_token uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now(),
  constraint feedback_v2_display_name_length check (display_name is null or char_length(display_name) <= 40),
  constraint feedback_v2_category_allowed check (category in ('主页建议', '内容纠错', '交流合作', '访客留言', '作品评价')),
  constraint feedback_v2_device_allowed check (device_type in ('手机', '平板', '电脑')),
  constraint feedback_v2_content_length check (char_length(content) between 2 and 1000),
  constraint feedback_v2_contact_length check (contact is null or char_length(contact) <= 200),
  constraint feedback_v2_image_path_format check (
    image_path is null or image_path ~ ('^' || id::text || '/[0-9a-f-]+\.(webp|gif)$')
  )
);

alter table public.feedback_messages_v2 enable row level security;
revoke all on public.feedback_messages_v2 from anon, authenticated;

-- 公开视图只暴露可公开字段，不包含联系方式和上传令牌。
create or replace view public.public_comments_v2
with (security_barrier = true)
as
select id, display_name, category, device_type, content, image_path, created_at
from public.feedback_messages_v2
where wants_public = true;

revoke all on public.public_comments_v2 from public;
grant select on public.public_comments_v2 to anon, authenticated;

-- 站主回复由你在 Supabase Table Editor 中手动填写。
create table if not exists public.feedback_replies (
  id bigint generated by default as identity primary key,
  comment_source text not null check (comment_source in ('legacy', 'v2')),
  comment_id bigint not null,
  reply_content text not null check (char_length(trim(reply_content)) between 1 and 1000),
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (comment_source, comment_id)
);

alter table public.feedback_replies enable row level security;
revoke all on public.feedback_replies from anon, authenticated;

create or replace view public.public_feedback_replies
with (security_barrier = true)
as
select id, comment_source, comment_id, reply_content, created_at, updated_at
from public.feedback_replies
where is_public = true;

revoke all on public.public_feedback_replies from public;
grant select on public.public_feedback_replies to anon, authenticated;

-- 标题已从新版接口移除。函数返回本次留言 ID 和一次性图片令牌。
create or replace function public.submit_feedback_v2(
  p_category text,
  p_content text,
  p_contact text,
  p_display_name text,
  p_wants_public boolean,
  p_device_type text
)
returns table (feedback_id bigint, upload_token uuid)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_row public.feedback_messages_v2;
begin
  if p_category not in ('主页建议', '内容纠错', '交流合作', '访客留言', '作品评价') then
    raise exception '无效的留言类型';
  end if;
  if p_device_type not in ('手机', '平板', '电脑') then
    raise exception '请选择手机、平板或电脑';
  end if;
  if char_length(trim(coalesce(p_content, ''))) not between 2 and 1000 then
    raise exception '留言内容应为 2 至 1000 字';
  end if;

  insert into public.feedback_messages_v2 (
    display_name, category, device_type, content, contact, wants_public
  ) values (
    nullif(left(trim(coalesce(p_display_name, '')), 40), ''),
    p_category,
    p_device_type,
    trim(p_content),
    nullif(left(trim(coalesce(p_contact, '')), 200), ''),
    coalesce(p_wants_public, false)
  ) returning * into new_row;

  return query select new_row.id, new_row.upload_token;
end;
$$;

revoke all on function public.submit_feedback_v2(text, text, text, text, boolean, text) from public;
grant execute on function public.submit_feedback_v2(text, text, text, text, boolean, text) to anon, authenticated;

-- 图片上传成功后，用留言 ID + 一次性令牌绑定 Storage 路径。
create or replace function public.attach_feedback_image_v2(
  p_feedback_id bigint,
  p_upload_token uuid,
  p_image_path text
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  changed integer;
begin
  if p_image_path !~ ('^' || p_feedback_id::text || '/' || p_upload_token::text || '\.(webp|gif)$') then
    raise exception '无效的图片路径';
  end if;

  update public.feedback_messages_v2
  set image_path = p_image_path,
      upload_token = gen_random_uuid()
  where id = p_feedback_id
    and upload_token = p_upload_token
    and wants_public = true
    and image_path is null;

  get diagnostics changed = row_count;
  return changed = 1;
end;
$$;

revoke all on function public.attach_feedback_image_v2(bigint, uuid, text) from public;
grant execute on function public.attach_feedback_image_v2(bigint, uuid, text) to anon, authenticated;

-- 创建公开图片桶；限制单文件 10 MB 和图片 MIME 类型。
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'feedback-images',
  'feedback-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Storage 策略通过安全函数验证“留言 ID + 一次性令牌”，避免匿名访客滥用图片桶。
create or replace function public.can_upload_feedback_image_v2(p_object_name text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.feedback_messages_v2 f
    where f.wants_public = true
      and f.image_path is null
      and p_object_name ~ ('^' || f.id::text || '/' || f.upload_token::text || '\.(webp|gif)$')
  );
$$;

revoke all on function public.can_upload_feedback_image_v2(text) from public;
grant execute on function public.can_upload_feedback_image_v2(text) to anon, authenticated;

drop policy if exists "feedback images anonymous upload" on storage.objects;
create policy "feedback images anonymous upload"
on storage.objects
for insert
to anon, authenticated
with check (
  bucket_id = 'feedback-images'
  and public.can_upload_feedback_image_v2(name)
);

commit;

-- 执行后可用以下语句确认对象已创建：
-- select * from public.public_comments_v2 limit 1;
-- select public.submit_feedback_v2('访客留言', '迁移测试留言', null, '测试访客', false, '电脑');
